image:
  repository: expediagroup/kubernetes-sidecar-injector
  tag: 1.1.0
  pullPolicy: IfNotPresent
  pullSecrets: []

replicaCount: 1

service:
  port: 443

container:
  port: 8443

podAnnotations: {}
podLabels: {}
podSecurityContext: {}

sidecars:
  dataKey: sidecars.yaml

selectors:
  injectPrefix: sidecar-injector.liveramp.com
  injectName: inject
  disableInjectLabel: disable-inject
  objectSelector: {}
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: NotIn
        values:
          - kube-system
          - kube-public
